# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "update"

  # Update NPM dependencies in packages.json
  - package-ecosystem: "npm"
    directory: "{{cookiecutter.project_slug}}/packages-json/"
    schedule:
      interval: "daily"
    labels:
      - "update"
